apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
    mongo-root-username: # generate username with base64 by this command ----- "echo -n 'username' | base64"
    mongo-root-password: # generate password with base64
