apiVersion: v1
kind: Pod
metadata:
  creationTimeStamp: null
  labels:
    run: demo
  name: demo
spec:
  containers:
    - image: busybox
      name: demo
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: Hello
          valueFrom:
            configMapKeyRef:
              name: demo2
              key: name
  restartPolicy: Never
status: {}
