apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-volume
spec:
  containers:
    - name: pod-sec
      image: nginx
      volumeMounts:
        - name: vol-secret
          mountPath: /etc/vol-secret
  volumes:
    - name: vol-secret
      secret:
        secretName: secret-for-volume
