# apiVersion: v1
# kind: Service
# metadata:
#   name: local-service
#   labels:
#     app: local-test
# spec:
#   ports:
#     - port: 80
#       name: stateul-vol
#   clusterIP: none
#   selector:
#     app: local-test
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-vol
spec:
  serviceName: "local-service"
  replicas: 3
  selector:
    matchLabels:
      app: local-test
  template:
    metadata:
      labels: 
        app: local-test
    spec:
      containers:
        - name: test-container
          image: k8s.gcr.io/busybox
          command:
          - "/bin/sh"
          args:
          - "-c"
          - "sleep 10000"
          volumeMounts:
          - name: local-vol
            mountPath: /usr/test-pod
  volumeClaimTemplates:
  - metadata:
      name: local-vol
    spec:
      storageClassName: local-path #using rancher for dynamic provisioning
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
  