CODE_CHANGES = getGitChanges()
pipeline {

    agent any
    environment = {
        NEW_VERSION = "1.3.0"
        SERVER_CREDENTIALS = credentials('server-credentials')
    }
    stages {

        stage("build") {
            when {
                expression {
                    BRANCH_NAME == 'dev' && CODE_CHANGES == true
                }
            }
            steps {
                echo 'building the application...'
                echo 'building done'
            }
        }

        stage("test") {
            when {
                expression {
                    BRANCH_NAME == 'dev'
                }
            }
            steps {
                echo 'testing  the application...'
            }
        }

        stage("deploy") {

            steps {
                echo 'deploying the application...'
                withCredentials([
                    usernamePassword(credentialsId: 'server-credentials', usernameVariable: USER, passwordVariable: PWD)
                ]) {
                    sh "curl -u $USER:$PWD -X POST http://localhost:8080/job/Deploy/build"
                }
                ]) {

                }
            }
        }
    }
}
