CODE_CHANGES = getGitChanges()
pipeline {

    agent any
    // environment = {
    //     NEW_VERSION = "1.3.0"
    //     SERVER_CREDENTIALS = credentials('server-credentials')
    // }
    parameters {
        choice(name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: '')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }
    stages {

        stage("build") {
            // when {
            //     expression {
            //         BRANCH_NAME == 'dev' && CODE_CHANGES == true
            //     }
            // }
            steps {
                echo 'building the application...'
                echo 'building done'
            }
        }

        stage("test") {
            when {
                expression {
                    params.executeTests == true // taking it from parameters section above
                    // BRANCH_NAME == 'dev'
                }
            }
            steps {
                echo 'testing  the application...'
            }
        }

        stage("deploy") {

            steps {
                echo 'deploying the application...'
                echo "deploying version ${params.VERSION}" // taking it from parameters section above
                // withCredentials([
                //     usernamePassword(credentialsId: 'server-credentials', usernameVariable: USER, passwordVariable: PWD)
                // ]) {
                //     sh "curl -u $USER:$PWD -X POST http://localhost:8080/job/Deploy/build"
                // }
                // ]) {

                // }
            }
        }
    }
}
